In [1]:
import pandas as pd
import numpy as np

In [29]:
empids = [101,102,103,104,105,106,107,108,109,110]
names = ["Adam", "Blake", "Clark", "Jake", "King", "Jones", "Tanishq", "Atharva", "Shantanu", "Tushar"]

In [47]:
emp_series=pd.Series(names,index=empids)
emp_series

101        Adam
102       Blake
103       Clark
104        Jake
105        King
106       Jones
107     Tanishq
108     Atharva
109    Shantanu
110      Tushar
dtype: str

In [51]:
type(emp_series)

pandas.Series

In [64]:
df = emp_series.reset_index()
df.columns = ["EmpID", "Name"]

print("\nDataFrame:")
print(df)

DataFrame:
   EmpID      Name
0    101      Adam
1    102     Blake
2    103     Clark
3    104      Jake
4    105      King
5    106     Jones
6    107   Tanishq
7    108   Atharva
8    109  Shantanu
9    110    Tushar

In [65]:
df

   EmpID      Name
0    101      Adam
1    102     Blake
2    103     Clark
3    104      Jake
4    105      King
5    106     Jones
6    107   Tanishq
7    108   Atharva
8    109  Shantanu
9    110    Tushar

In [66]:
df.head()

   EmpID   Name
0    101   Adam
1    102  Blake
2    103  Clark
3    104   Jake
4    105   King

In [67]:
df.tail()

   EmpID      Name
5    106     Jones
6    107   Tanishq
7    108   Atharva
8    109  Shantanu
9    110    Tushar

In [68]:
df.head(2)

   EmpID   Name
0    101   Adam
1    102  Blake

In [69]:
df.tail(2)

   EmpID      Name
8    109  Shantanu
9    110    Tushar

In [71]:
df.loc[4, "Name"]

'King'

In [72]:
df.loc[3,"Name"]

'Jake'

In [75]:
df.to_csv("MyRecord.csv", index=False)

In [78]:
# Assignment 1 -> 2

In [83]:
df= pd.read_csv("Advertising.csv")
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [82]:
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [84]:
df.tail()

        TV  radio  newspaper  sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [85]:
df.columns

Index(['TV', 'radio', 'newspaper', 'sales'], dtype='str')

In [86]:
df.tail(3)

        TV  radio  newspaper  sales
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [87]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [89]:
df.dtypes

TV           float64
radio        float64
newspaper    float64
sales        float64
dtype: object

In [92]:
df.isnull().sum()

TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [95]:
df1 = df.drop('radio', axis = 1)
df1.head(10)

      TV  newspaper  sales
0  230.1       69.2   22.1
1   44.5       45.1   10.4
2   17.2       69.3    9.3
3  151.5       58.5   18.5
4  180.8       58.4   12.9
5    8.7       75.0    7.2
6   57.5       23.5   11.8
7  120.2       11.6   13.2
8    8.6        1.0    4.8
9  199.8       21.2   10.6

In [96]:
df["updated_sales"] = df["sales"] * 1.10

In [97]:
df

        TV  radio  newspaper  sales  updated_sales
0    230.1   37.8       69.2   22.1          24.31
1     44.5   39.3       45.1   10.4          11.44
2     17.2   45.9       69.3    9.3          10.23
3    151.5   41.3       58.5   18.5          20.35
4    180.8   10.8       58.4   12.9          14.19
..     ...    ...        ...    ...            ...
195   38.2    3.7       13.8    7.6           8.36
196   94.2    4.9        8.1    9.7          10.67
197  177.0    9.3        6.4   12.8          14.08
198  283.6   42.0       66.2   25.5          28.05
199  232.1    8.6        8.7   13.4          14.74

[200 rows x 5 columns]

In [99]:
df.shape

(200, 5)

In [107]:
df.max()

TV               296.4
radio             49.6
newspaper        114.0
sales             27.0
updated_sales     29.7
dtype: float64

In [108]:
df.min()

TV               0.70
radio            0.00
newspaper        0.30
sales            1.60
updated_sales    1.76
dtype: float64

In [109]:
df.mean()

TV               147.04250
radio             23.26400
newspaper         30.55400
sales             14.02250
updated_sales     15.42475
dtype: float64

In [110]:
df.median()

TV               149.75
radio             22.90
newspaper         25.75
sales             12.90
updated_sales     14.19
dtype: float64

In [111]:
df.std()

TV               85.854236
radio            14.846809
newspaper        21.778621
sales             5.217457
updated_sales     5.739202
dtype: float64

In [112]:
df.describe()

               TV       radio   newspaper       sales  updated_sales
count  200.000000  200.000000  200.000000  200.000000     200.000000
mean   147.042500   23.264000   30.554000   14.022500      15.424750
std     85.854236   14.846809   21.778621    5.217457       5.739202
min      0.700000    0.000000    0.300000    1.600000       1.760000
25%     74.375000    9.975000   12.750000   10.375000      11.412500
50%    149.750000   22.900000   25.750000   12.900000      14.190000
75%    218.825000   36.525000   45.100000   17.400000      19.140000
max    296.400000   49.600000  114.000000   27.000000      29.700000

In [115]:
# 3

In [123]:
df2 = pd.read_csv("Salaries .csv")

In [124]:
df2.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [125]:
df2.head(10)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

In [130]:
df2.tail()

         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [131]:
df2.tail(10)

         rank discipline  phd  service     sex  salary
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [132]:
df2.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='str')

In [133]:
df2.shape

(78, 6)

In [134]:
df2.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [136]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     str
 1   discipline  78 non-null     str
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     str
 5   salary      78 non-null     int64
dtypes: int64(3), str(3)
memory usage: 3.8 KB

In [137]:
df2.dtypes

rank            str
discipline      str
phd           int64
service       int64
sex             str
salary        int64
dtype: object

In [141]:
df2.max(numeric_only=True)

phd            56
service        51
salary     186960
dtype: int64

In [142]:
df2.min(numeric_only=True)

phd            1
service        0
salary     57800
dtype: int64

In [143]:
df2.mean(numeric_only=True)

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

In [144]:
df2.median(numeric_only=True)

phd            18.5
service        14.5
salary     104671.0
dtype: float64

In [145]:
df2.std(numeric_only=True)

phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64

In [146]:
df2.isnull().sum()

rank          0
discipline    0
phd           0
service       0
sex           0
salary        0
dtype: int64

In [147]:
df2.dropna()

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [149]:
df2[df2["salary"] > 50000]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [150]:
df2[df2["salary"]<20000]

Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []

In [152]:
df2[(df2["salary"]>=20000) & (df2["salary"]<=50000)]

Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []

In [153]:
df2[df2["salary"]>100000]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
7        Prof          A   18       18    Male  126300
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
65       Prof          A   36       19  Female  117555
69       Prof          A   28        7  Female  116450
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [154]:
df2[df2["salary"]<100000]

         rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
6   AssocProf          A   20       17    Male   81285
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
12   AsstProf          B    1        0    Male   88000
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
20   AsstProf          B    4        4    Male   92000
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
38   AsstProf          B    4        3    Male   91000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
46   AsstProf          B   11        3  Female   74692
50   AsstProf          B   10        5  Female   97032
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
60   AsstProf          B    3        3  Female   92000
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065

In [155]:
df2[df2["discipline"]=='A']

         rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
32       Prof          A   27       19    Male  103275
37       Prof          A   20        8    Male  102000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [156]:
df2[df2["discipline"]=='B']

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
4        Prof          B   20       18    Male  104800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
20   AsstProf          B    4        4    Male   92000
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312

In [157]:
df2[df2["service"]>10]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
29       Prof          B   21       20    Male  123683
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
51       Prof          B   20       14  Female  127512
54  AssocProf          A   25       22  Female   62884
58       Prof          B   36       26  Female  144651
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
67       Prof          A   17       11  Female   90450
72       Prof          B   24       15  Female  161101
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [158]:
df2[df2["service"]<5]

        rank discipline  phd  service     sex  salary
12  AsstProf          B    1        0    Male   88000
15      Prof          B   17        3    Male  150480
16  AsstProf          B    8        3    Male   75044
17  AsstProf          B    4        0    Male   92000
20  AsstProf          B    4        4    Male   92000
22  AsstProf          A    4        2    Male   73000
23  AsstProf          A    2        0    Male   85000
28  AsstProf          B    7        2    Male   91300
38  AsstProf          B    4        3    Male   91000
42  AsstProf          B    4        2  Female   80225
43  AsstProf          B    5        0  Female   77000
46  AsstProf          B   11        3  Female   74692
52      Prof          A   12        0  Female  105000
53  AsstProf          A    5        3  Female   73500
55  AsstProf          A    2        0  Female   72500
57  AsstProf          A    3        1  Female   72500
60  AsstProf          B    3        3  Female   92000
68  AsstProf          A    4        2  Female   77500
70  AsstProf          A    8        3  Female   78500

In [161]:
df2[["phd","salary"]]

    phd  salary
0    56  186960
1    12   93000
2    23  110515
3    40  131205
4    20  104800
..  ...     ...
73   18  105450
74   19  104542
75   17  124312
76   28  109954
77   23  109646

[78 rows x 2 columns]

In [162]:
df2[['rank','sex','salary']]

         rank     sex  salary
0        Prof    Male  186960
1        Prof    Male   93000
2        Prof    Male  110515
3        Prof    Male  131205
4        Prof    Male  104800
..        ...     ...     ...
73       Prof  Female  105450
74  AssocProf  Female  104542
75       Prof  Female  124312
76       Prof  Female  109954
77       Prof  Female  109646

[78 rows x 3 columns]

In [163]:
df2.drop("salary", axis=1)

         rank discipline  phd  service     sex
0        Prof          B   56       49    Male
1        Prof          A   12        6    Male
2        Prof          A   23       20    Male
3        Prof          A   40       31    Male
4        Prof          B   20       18    Male
..        ...        ...  ...      ...     ...
73       Prof          B   18       10  Female
74  AssocProf          B   19        6  Female
75       Prof          B   17       17  Female
76       Prof          A   28       14  Female
77       Prof          A   23       15  Female

[78 rows x 5 columns]

In [164]:
df2[['rank', 'service', 'salary']].head(50)

         rank  service  salary
0        Prof       49  186960
1        Prof        6   93000
2        Prof       20  110515
3        Prof       31  131205
4        Prof       18  104800
5        Prof       20  122400
6   AssocProf       17   81285
7        Prof       18  126300
8        Prof       19   94350
9        Prof       51   57800
10       Prof       33  128250
11       Prof       23  134778
12   AsstProf        0   88000
13       Prof       33  162200
14       Prof       19  153750
15       Prof        3  150480
16   AsstProf        3   75044
17   AsstProf        0   92000
18       Prof        7  107300
19       Prof       27  150500
20   AsstProf        4   92000
21       Prof       30  103106
22   AsstProf        2   73000
23   AsstProf        0   85000
24       Prof       23   91100
25       Prof       31   99418
26       Prof       19  148750
27       Prof       43  155865
28   AsstProf        2   91300
29       Prof       20  123683
30  AssocProf        7  107008
31       Prof       21  155750
32       Prof       19  103275
33       Prof       18  120000
34  AssocProf        8  119800
35       Prof       23  126933
36       Prof       45  146856
37       Prof        8  102000
38   AsstProf        3   91000
39       Prof       18  129000
40       Prof       36  137000
41  AssocProf        8   74830
42   AsstProf        2   80225
43   AsstProf        0   77000
44       Prof       19  151768
45       Prof       25  140096
46   AsstProf        3   74692
47  AssocProf       11  103613
48       Prof       17  111512
49       Prof       18  122960

In [166]:
df2[df2["rank"] == "Prof"]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   12        6    Male   93000
2   Prof          A   23       20    Male  110515
3   Prof          A   40       31    Male  131205
4   Prof          B   20       18    Male  104800
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
8   Prof          A   29       19    Male   94350
9   Prof          A   51       51    Male   57800
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
18  Prof          A   19        7    Male  107300
19  Prof          A   29       27    Male  150500
21  Prof          A   33       30    Male  103106
24  Prof          A   30       23    Male   91100
25  Prof          B   35       31    Male   99418
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
32  Prof          A   27       19    Male  103275
33  Prof          B   18       18    Male  120000
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
37  Prof          A   20        8    Male  102000
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
48  Prof          B   17       17  Female  111512
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
52  Prof          A   12        0  Female  105000
58  Prof          B   36       26  Female  144651
63  Prof          A   29       27  Female   91000
65  Prof          A   36       19  Female  117555
67  Prof          A   17       11  Female   90450
69  Prof          A   28        7  Female  116450
72  Prof          B   24       15  Female  161101
73  Prof          B   18       10  Female  105450
75  Prof          B   17       17  Female  124312
76  Prof          A   28       14  Female  109954
77  Prof          A   23       15  Female  109646

In [168]:
df2[df2["rank"]=="AssocProf"]

         rank discipline  phd  service     sex  salary
6   AssocProf          A   20       17    Male   81285
30  AssocProf          B    9        7    Male  107008
34  AssocProf          B   12        8    Male  119800
41  AssocProf          A   13        8  Female   74830
47  AssocProf          B   11       11  Female  103613
54  AssocProf          A   25       22  Female   62884
56  AssocProf          A   10        8  Female   77500
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
64  AssocProf          A   26       24  Female   73300
71  AssocProf          B   12        9  Female   71065
74  AssocProf          B   19        6  Female  104542